class ChatExchange {
  late String id;
  late String product1;
  late String product2;
  late String requester1;
  late List<String> messages;
  late String status;

  ChatExchange({
    required this.id,
    required this.product1,
    required this.product2,
    required this.requester1,
    required this.messages,
    required this.status,
  });


  ChatExchange.createWithProducts({
    required this.product1,
    required this.product2,
    required this.requester1,
    // ... (otras propiedades)
  }) {
    id = 'new';
    messages = [];
    status = 'pending';
  }
}




/*
// Generated by https://quicktype.io

//import 'package:aplicacion_mundo_otaku/features/auth/domain/domain.dart';
import 'package:aplicacion_mundo_otaku/features/products/domain/domain.dart';

class ChatExchange {
  List<dynamic> messages;
  String id;
  String status;
  Product product1;
  Product product2;
  Product requester1;

  ChatExchange({
    required this.messages,
    required this.id,
    required this.status,
    required this.product1,
    required this.product2,
    required this.requester1,
  });
}

/*
class Product1 {
  String id;
  String title;
  String typeOf;
  int tomo;
  String description;
  String sizeOf;
  String gender;
  String demographic;
  List<String> tags;

  Product1({
    this.id,
    this.title,
    this.typeOf,
    this.tomo,
    this.description,
    this.sizeOf,
    this.gender,
    this.demographic,
    this.tags,
  });
}
*/
*/