// Generated by https://quicktype.io
import 'package:aplicacion_mundo_otaku/features/auth/domain/domain.dart';

class Product {
  String id;
  String title;
  String typeOf;
  int tomo;
  String description;
  String? slug;
  String sizeOf;
  String gender;
  String demographic;
  List<String> tags;
  List<String> images;
  User? user;

  Product({
    required this.id,
    required this.title,
    required this.typeOf,
    required this.description,
    required this.tomo,
    required this.sizeOf,
    required this.gender,
    required this.demographic,
    required this.tags,
    required this.images,
    this.user,
  });

  /// Si la ficha debe mostrar el número de tomo.
  ///
  /// En un manga, siempre: **el tomo 0 existe** (precuelas que salen ya
  /// avanzada la serie) y tiene que verse. En Ropa, Taza y Otros el 0
  /// significa "no aplica", así que solo se muestra si tiene un número
  /// mayor, como una novela ligera publicada como "Otros".
  bool get muestraTomo => typeOf == 'Manga' || tomo > 0;
}
