// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM7cPf57OW8uqXhg64m_S9VRMuU1Wo6iw',
    appId: '1:779829280027:web:1ee26c806e9cf47f0727be',
    messagingSenderId: '779829280027',
    projectId: 'mundo-otaku-crud',
    authDomain: 'mundo-otaku-crud.firebaseapp.com',
    storageBucket: 'mundo-otaku-crud.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyfgreLjNt-205z_pSi-tMi1lDp0dITm8',
    appId: '1:779829280027:android:b3e2cd5162602fd10727be',
    messagingSenderId: '779829280027',
    projectId: 'mundo-otaku-crud',
    storageBucket: 'mundo-otaku-crud.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8_lgTEFkC6Wc10kxYF8KSt3ULoE2_qYA',
    appId: '1:779829280027:ios:aa2d56705182df490727be',
    messagingSenderId: '779829280027',
    projectId: 'mundo-otaku-crud',
    storageBucket: 'mundo-otaku-crud.appspot.com',
    iosBundleId: 'com.example.aplicacionMundoOtaku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8_lgTEFkC6Wc10kxYF8KSt3ULoE2_qYA',
    appId: '1:779829280027:ios:464f14dd2c45c3e60727be',
    messagingSenderId: '779829280027',
    projectId: 'mundo-otaku-crud',
    storageBucket: 'mundo-otaku-crud.appspot.com',
    iosBundleId: 'com.example.aplicacionMundoOtaku.RunnerTests',
  );
}
